// Auto-generated by: npx supabase gen types typescript --local
// Run this command after connecting to Supabase project to regenerate
// This placeholder will be replaced with actual generated types

export type ClassificationResult = 'A_VOIR' | 'FILTRE' | 'BLOQUE'
export type QueueStatus = 'pending' | 'processing' | 'completed' | 'failed'

// Placeholder types — will be replaced by supabase gen types
export type Database = {
  public: {
    Tables: {
      user_integrations: {
        Row: {
          id: string
          user_id: string
          provider: string
          email: string
          access_token: string
          refresh_token: string
          expires_at: string
          scopes: string[]
          watch_expiry: string | null
          watch_history_id: string | null
          status: 'active' | 'revoked' | 'expired'
          created_at: string
          updated_at: string
        }
      }
      email_classifications: {
        Row: {
          id: string
          user_id: string
          gmail_message_id: string
          classification_result: ClassificationResult
          confidence_score: number
          summary: string | null
          source: 'fingerprint' | 'llm'
          processing_time_ms: number | null
          idempotency_key: string | null
          created_at: string
        }
      }
      email_queue_items: {
        Row: {
          id: string
          user_id: string
          gmail_message_id: string
          gmail_history_id: string | null
          status: QueueStatus
          retry_count: number
          claimed_at: string | null
          created_at: string
          processed_at: string | null
          error_message: string | null
        }
      }
      usage_counters: {
        Row: {
          id: string
          user_id: string
          date_bucket: string
          count: number
        }
      }
      user_pipeline_health: {
        Row: {
          id: string
          user_id: string
          last_classified_at: string | null
          watch_expires_at: string | null
          mode: 'active' | 'paused' | 'polling'
          pause_reason: string | null
          created_at: string
          updated_at: string
        }
      }
      llm_metrics_hourly: {
        Row: {
          id: string
          hour_bucket: string
          bypass_rate: number | null
          total_cost_eur: number | null
          users_count: number | null
          created_at: string
        }
      }
      processed_webhook_events: {
        Row: {
          id: string
          event_id: string
          event_type: string | null
          processed_at: string
        }
      }
      recap_tokens: {
        Row: {
          id: string
          user_id: string
          token: string
          email_id: string
          recap_date: string
          used_at: string | null
          expires_at: string
          created_at: string
        }
      }
      reclassification_requests: {
        Row: {
          id: string
          user_id: string
          email_id: string
          source: string
          token_id: string | null
          status: string
          created_at: string
          processed_at: string | null
        }
      }
    }
    Functions: {
      increment_usage_counter: {
        Args: { p_user_id: string; p_date: string }
        Returns: number | null
      }
      get_stale_pipeline_count: {
        Args: { threshold_minutes?: number }
        Returns: number
      }
    }
    Enums: {
      classification_result: ClassificationResult
      queue_status: QueueStatus
    }
  }
}
